# Farmhouse Yeasts Culturess Heterogeneity

```{r, echo=FALSE, include=FALSE}
# load required libraries
up_packages = c("circlize", "clusterProfiler", "ComplexHeatmap", "ggplot2", "grid", "gridExtra", "magrittr", "RColorBrewer",
                "org.Sc.sgd.db")
lapply(up_packages, require, character.only = TRUE)

# set working directory
mainDir = "/home/Andrea/Desktop/kveiks/manuscript/plotting_data/"
knitr::opts_knit$set(root.dir = mainDir)
```



## Vaaa








```{r}


# load libraries
library("dplyr")
library("ggplot2")
library("ggpubr")
library("grid")
library("gridExtra")
library("plyr")
library("RColorBrewer")


# change working directory
setwd("/home/Andrea/Desktop/kveiks/")


# import dataset
kveik = read.delim("all_plusKV.heterozygous.positions.txt", header = TRUE)


# sort 
kveik$Pop = factor(
  kveik$Pop,
  levels = c("Farmhouse", "Asian", "Beer1", "Beer2", "Bread",
             "Mixed", "Mosaic", "Sake", "Wild", "Wine")
)
kveik$Pop = relevel(kveik$Pop, "Farmhouse")

# t-test
tests = ggpubr::compare_means(HET_CT ~ Pop, data = kveik,
                              #ref.group = "Farmhouse",
                              method = "anova")

# prepare count labels
stat_box_data <- function(y) {
  return( 
    data.frame(
      y = 6,
      #sign =tests1[which(tests1$group2 == y),]$p.signif,
      label = paste('n =', length(y))
    )
  )
}

# open printing file
pdf(file = "all_plusKV.heterozygous.positions.pdf",
    width = 12,
    height = 8)

# plot
ggplot(kveik, aes(x = Pop, y = HET_CT)) +
  geom_point(position = position_jitter(width = 0.25),
             shape = 21, fill = "grey50", 
             alpha = 0.25) +
  geom_boxplot(fill = NA, outlier.shape = NA) +
  geom_vline(xintercept = 1.5) +
  geom_vline(xintercept = 2.5, color = "grey75") +
  geom_vline(xintercept = 3.5, color = "grey75") +
  geom_vline(xintercept = 4.5, color = "grey75") +
  geom_vline(xintercept = 5.5, color = "grey75") +
  geom_vline(xintercept = 6.5, color = "grey75") +
  geom_vline(xintercept = 7.5, color = "grey75") +
  geom_vline(xintercept = 8.5, color = "grey75") +
  geom_vline(xintercept = 9.5, color = "grey75") +
  geom_vline(xintercept = 10.5, color = "grey75") +
  geom_vline(xintercept = 11.5, color = "grey75") +
  geom_vline(xintercept = 12.5, color = "grey75") +
  stat_summary(fun.data = stat_box_data, geom = "text",
               hjust = 0.5, vjust = 0.9) +
  annotate("text", x = 2,  y = 1290000, label = c(tests$p.signif)[[1]]) +
  annotate("text", x = 3,  y = 1290000, label = c(tests$p.signif)[[2]]) +
  annotate("text", x = 4,  y = 1290000, label = c(tests$p.signif)[[3]]) +
  annotate("text", x = 5,  y = 1290000, label = c(tests$p.signif)[[4]]) +
  annotate("text", x = 6,  y = 1290000, label = c(tests$p.signif)[[5]]) +
  annotate("text", x = 7,  y = 1290000, label = c(tests$p.signif)[[6]]) +
  annotate("text", x = 8,  y = 1290000, label = c(tests$p.signif)[[7]]) +
  annotate("text", x = 9,  y = 1290000, label = c(tests$p.signif)[[8]]) +
  annotate("text", x = 10,  y = 1290000, label = c(tests$p.signif)[[9]]) +
  scale_y_log10(labels = scales::comma,
                limits = c(1, 1300000)) +
  labs(title = "Heterozygosity in yeast populations",
       x = "Populations",
       y = "log10 heterozygous positions") +
  theme(plot.title = element_text(hjust = 0.5, size = 24),
        axis.text.x = element_text(hjust = 0.95, angle = 30, size = 16),
        axis.text.y = element_text(size = 16),
        axis.title = element_text(size = 18),
        legend.position = "none",
        panel.background = element_rect(colour = "black", fill = NA),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_line(colour = "grey75"),
        panel.grid.minor.y = element_blank())


# plot
ggplot(kveik, aes(x = Pop, y = HET_CT)) +
  geom_point(shape = "-", size = 3.5) +
  geom_boxplot(fill = "grey95", alpha = 0.75, width = 0.25,
               position = position_nudge(x = -0.2),
               outlier.colour = NA) +
  ggdist::stat_halfeye(fill = "grey95", alpha = 0.75, slab_color = "grey45", slab_size = 0.25, 
                       adjust = 5, justification = -0.05, .width = 0, point_colour = NA) +
  geom_vline(xintercept = 1.5) +
  stat_summary(fun.data = stat_box_data, geom = "text",
               hjust = 0.5, vjust = 0.9) +
  annotate("text", x = 2,  y = 1290000, label = c(tests$p.signif)[[1]]) +
  annotate("text", x = 3,  y = 1290000, label = c(tests$p.signif)[[2]]) +
  annotate("text", x = 4,  y = 1290000, label = c(tests$p.signif)[[3]]) +
  annotate("text", x = 5,  y = 1290000, label = c(tests$p.signif)[[4]]) +
  annotate("text", x = 6,  y = 1290000, label = c(tests$p.signif)[[5]]) +
  annotate("text", x = 7,  y = 1290000, label = c(tests$p.signif)[[6]]) +
  annotate("text", x = 8,  y = 1290000, label = c(tests$p.signif)[[7]]) +
  annotate("text", x = 9,  y = 1290000, label = c(tests$p.signif)[[8]]) +
  annotate("text", x = 10,  y = 1290000, label = c(tests$p.signif)[[9]]) +
  scale_y_log10(labels = scales::comma,
                limits = c(1, 1300000)) +
  labs(title = "Heterozygosity in yeast populations",
       x = "Populations",
       y = "log10 heterozygous positions") +
  theme(plot.title = element_text(hjust = 0.5, size = 24),
        axis.text.x = element_text(hjust = 0.95, angle = 30, size = 16),
        axis.text.y = element_text(size = 16),
        axis.title = element_text(size = 18),
        legend.position = "none",
        panel.background = element_rect(colour = "black", fill = NA),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_line(colour = "grey75"),
        panel.grid.minor.y = element_blank())



########## GRAPHS WITHOUT STAT TAHT IS BROKEN
########## SEE https://github.com/kassambara/ggpubr/issues/572

# plot
ggplot(kveik, aes(x = Pop, y = HET_CT)) +
  geom_point(aes(fill = Pop),
             position = position_jitter(width = 0.25),
             shape = 21, 
             alpha = 0.375,
             size = 3) +
  geom_boxplot(fill = NA, outlier.shape = NA) +
  geom_vline(xintercept = 1.5) +
  scale_fill_manual(values = c("#20E0E3", "#DD4C65", "#61CF4F", "#2998E5", "#F3C200",
                               "#CC09BB", "#050505", "#911EB4", "#F032E6", "#BCF60C")) +
  stat_summary(fun.data = stat_box_data, geom = "text",
               hjust = 0.5, vjust = -50) +
  scale_y_continuous(labels = scales::comma,
                     limits = c(1, 100000)) +
  labs(title = "Heterozygosity in yeast populations",
       x = "Populations",
       y = "# heterozygous positions") +
  theme(plot.title = element_text(hjust = 0.5, size = 24),
        axis.text.x = element_text(hjust = 0.95, angle = 30, size = 16),
        axis.text.y = element_text(size = 16),
        axis.title = element_text(size = 18),
        legend.position = "none",
        panel.background = element_rect(colour = "black", fill = NA),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_line(colour = "grey75"),
        panel.grid.minor.y = element_blank())




# plot
kveik_comp = kveik[which(kveik$Pop == "Farmhouse" & kveik$Subpopulation != "Beer1"), ]
kveik_comp$Subpopulation = "All Farmhouse"
kveik_comp = rbind(kveik_comp, kveik[which(kveik$Pop == "Farmhouse" & kveik$Subpopulation != "Beer1"), ])

ggplot(kveik_comp, aes(x = Subpopulation, y = HET_CT)) +
  geom_point(aes(fill = Subpopulation),
             position = position_jitter(width = 0.25),
             shape = 21, 
             alpha = 0.375,
             size = 3) +
  geom_boxplot(fill = NA, outlier.shape = NA) +
  geom_vline(xintercept = 1.5) +
  scale_fill_manual(values = c("#20E0E3", "#FFDA00", "#0571B0", "#92C5DE", "#A6611A", "#909090")) +
  scale_y_continuous(labels = scales::comma,
                limits = c(1, 100000)) +
  stat_summary(fun.data = stat_box_data, geom = "text",
               hjust = 0.5, vjust = -50) +
  labs(title = "Heterozygosity in Farmhouse yeasts subpopulations",
       x = "Subpopulations",
       y = "# heterozygous positions") +
  theme(plot.title = element_text(hjust = 0.5, size = 24),
        axis.text.x = element_text(hjust = 0.95, angle = 30, size = 16),
        axis.text.y = element_text(size = 16),
        axis.title = element_text(size = 18),
        legend.position = "none",
        panel.background = element_rect(colour = "black", fill = NA),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_line(colour = "grey75"),
        panel.grid.minor.y = element_blank())

#
kveik_comp2 = kveik[which(kveik$Pop == "Farmhouse" & kveik$Subpopulation != "Beer1"), ]
kveik_comp2$Subpopulation = "All Farmhouse"
kveik_comp2 = rbind(kveik_comp2, kveik)
kveik_comp2$Subpopulation = factor(
  kveik_comp2$Subpopulation,
  levels = c("All Farmhouse",
             "Baltic", "Gong", "Kveik", "Russian", "Wild",
             "Beer1", "Beer2", "Mixed", "Mosaic", "Others")
)

ggplot(kveik_comp2, aes(x = Subpopulation, y = HET_CT)) +
  geom_point(aes(fill = Subpopulation),
             position = position_jitter(width = 0.25),
             shape = 21, 
             alpha = 0.375,
             size = 3) +
  geom_boxplot(fill = NA, outlier.shape = NA) +
  geom_vline(xintercept = 1.5) +
  geom_vline(xintercept = 6.5) +
  scale_y_continuous(labels = scales::comma,
                     limits = c(1, 100000)) +
  scale_fill_manual(values = c("#20E0E3",
                               "#FFDA00", "#0571B0", "#92C5DE", "#A6611A", "#909090",
                               "#61CF4F", "#CC09BB", "#050505", "salmon")) +
  stat_summary(fun.data = stat_box_data, geom = "text",
               hjust = 0.5, vjust = -50) +
  labs(title = "Heterozygosity in Farmhouse yeasts subpopulations",
       x = "Subpopulations",
       y = "# heterozygous positions") +
  theme(plot.title = element_text(hjust = 0.5, size = 24),
        axis.text.x = element_text(hjust = 0.95, angle = 30, size = 16),
        axis.text.y = element_text(size = 16),
        axis.title = element_text(size = 18),
        legend.position = "none",
        panel.background = element_rect(colour = "black", fill = NA),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_line(colour = "grey75"),
        panel.grid.minor.y = element_blank())



```



