# Abstract {.unnumbered}

Since its inception over 10.000 years ago, beer brewing transformed from a domestic activity based on uncontrolled spontaneous fermentations into a highly optimized industrial process that uses pure single-strain starter cultures of *Saccharomyces* yeasts. Along with the storage of frozen yeast stocks, this shift halted the domestication process of beer yeasts and led to a massive loss of beer yeast biodiversity. However, a few traditional farmhouse brewers in Northern and Eastern Europe still rely on artisanal fermentation methods, using mixed cultures of yeasts that are passed on from one fermentation to the next. We genetically and phenotypically analyzed 1760 isolates from 44 traditional European farmhouse ale yeast cultures from Norway, Latvia, Lithuania and Russia. We find that farmhouse cultures harbour remarkable genetic diversity, from nearly pure S. cerevisiae strains to intricate communities of over 30 unique variants. Farmhouse yeast genomes exhibit clear geographic structuring, but also reveal signs of within-culture mating and occasional admixture between populations, alongside lineage-specific genomic features, such as a horizontally transferred gene cluster unique to Baltic strains. Large-scale phenotyping showed that the farmhouse yeasts show much greater stress tolerance and a more diverse flavour production profile compared to current industrial beer strains. Together, our study reveals the complex structure and enormous diversity of microbial communities in traditional fermentations and provides a reservoir of new yeast strains that could drive a next wave of beer innovation.
